name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Lint & Build
        working-directory: "."
        run: |
          npm ci
          npm run build